title: "Soft Matter Group @ DAMTP"
description: "Research in soft condensed matter, nonequilibrium stat mech, active matter."
url: "https://softmattergroupcambridge.github.io"
baseurl: "/group-website"
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-sitemap
permalink: pretty
nav: nav